// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum ItemType {
  WEAPON,
  ARMOR,
  TOOL,
  RESOURCE,
  CONSUMABLE,
  AMMUNITION
}

enum EquipSlot {
  WEAPON,
  SHIELD,
  HELMET,
  BODY,
  LEGS,
  ARROWS
}

enum MobType {
  GOBLIN,
  BANDIT,
  BARBARIAN,
  HOBGOBLIN,
  GUARD,
  DARK_WARRIOR,
  BLACK_KNIGHT,
  ICE_WARRIOR,
  DARK_RANGER
}

enum ResourceType {
  TREE,
  FISHING_SPOT,
  FIRE
}

enum CombatStyle {
  ACCURATE,
  AGGRESSIVE,
  DEFENSIVE,
  CONTROLLED
}
