// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerData } from "./tables/Player.sol";
import { Position, PositionData } from "./tables/Position.sol";
import { Health, HealthData } from "./tables/Health.sol";
import { CombatSkills, CombatSkillsData } from "./tables/CombatSkills.sol";
import { GatheringSkills, GatheringSkillsData } from "./tables/GatheringSkills.sol";
import { InventorySlot, InventorySlotData } from "./tables/InventorySlot.sol";
import { Equipment, EquipmentData } from "./tables/Equipment.sol";
import { ItemMetadata, ItemMetadataData } from "./tables/ItemMetadata.sol";
import { Mob, MobData } from "./tables/Mob.sol";
import { MobLootTable, MobLootTableData } from "./tables/MobLootTable.sol";
import { Resource, ResourceData } from "./tables/Resource.sol";
import { Coins, CoinsData } from "./tables/Coins.sol";
import { ItemInstance, ItemInstanceData } from "./tables/ItemInstance.sol";
import { PendingTrade, PendingTradeData } from "./tables/PendingTrade.sol";
import { CombatTarget, CombatTargetData } from "./tables/CombatTarget.sol";
import { WorldConfig, WorldConfigData } from "./tables/WorldConfig.sol";
