// Environment presets for ThreeViewer
export const ENVIRONMENTS = {
  neutral: {
    name: "Neutral",
    bgColor: "#0a0a0a",
    ambientColor: "#ffffff",
    ambientIntensity: 0.5,
    keyLightColor: "#ffffff",
    keyLightIntensity: 1,
    fillLightColor: "#4080ff",
    fillLightIntensity: 0.5,
    rimLightColor: "#ffffff",
    rimLightIntensity: 0.3,
  },
  studio: {
    name: "Studio",
    bgColor: "#1a1a1a",
    ambientColor: "#ffffff",
    ambientIntensity: 0.7,
    keyLightColor: "#fffaf0",
    keyLightIntensity: 1.2,
    fillLightColor: "#e0f0ff",
    fillLightIntensity: 0.6,
    rimLightColor: "#ffffff",
    rimLightIntensity: 0.5,
  },
  sunset: {
    name: "Sunset",
    bgColor: "#1a0f0a",
    ambientColor: "#ff9060",
    ambientIntensity: 0.6,
    keyLightColor: "#ffb366",
    keyLightIntensity: 1.1,
    fillLightColor: "#4060a0",
    fillLightIntensity: 0.4,
    rimLightColor: "#ff6b35",
    rimLightIntensity: 0.4,
  },
  cool: {
    name: "Cool",
    bgColor: "#0a0f1a",
    ambientColor: "#8090ff",
    ambientIntensity: 0.5,
    keyLightColor: "#b0c0ff",
    keyLightIntensity: 1,
    fillLightColor: "#6080ff",
    fillLightIntensity: 0.5,
    rimLightColor: "#a0b0ff",
    rimLightIntensity: 0.3,
  },
};
