// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ItemInstanceData {
  uint16 itemId;
  address owner;
  bool isMinted;
  uint256 mintedTokenId;
  uint256 createdAt;
  int32 x;
  int32 y;
  int32 z;
  bool isOnGround;
}

library ItemInstance {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "hyperscape", name: "ItemInstance", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746268797065727363617065000000004974656d496e7374616e636500000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0064090002140120200404040100000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint16, address, bool, uint256, uint256, int32, int32, int32, bool)
  Schema constant _valueSchema = Schema.wrap(0x006409000161601f1f2323236000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "instanceId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](9);
    fieldNames[0] = "itemId";
    fieldNames[1] = "owner";
    fieldNames[2] = "isMinted";
    fieldNames[3] = "mintedTokenId";
    fieldNames[4] = "createdAt";
    fieldNames[5] = "x";
    fieldNames[6] = "y";
    fieldNames[7] = "z";
    fieldNames[8] = "isOnGround";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get itemId.
   */
  function getItemId(bytes32 instanceId) internal view returns (uint16 itemId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Get itemId.
   */
  function _getItemId(bytes32 instanceId) internal view returns (uint16 itemId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint16(bytes2(_blob)));
  }

  /**
   * @notice Set itemId.
   */
  function setItemId(bytes32 instanceId, uint16 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((itemId)), _fieldLayout);
  }

  /**
   * @notice Set itemId.
   */
  function _setItemId(bytes32 instanceId, uint16 itemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((itemId)), _fieldLayout);
  }

  /**
   * @notice Get owner.
   */
  function getOwner(bytes32 instanceId) internal view returns (address owner) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get owner.
   */
  function _getOwner(bytes32 instanceId) internal view returns (address owner) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set owner.
   */
  function setOwner(bytes32 instanceId, address owner) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((owner)), _fieldLayout);
  }

  /**
   * @notice Set owner.
   */
  function _setOwner(bytes32 instanceId, address owner) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((owner)), _fieldLayout);
  }

  /**
   * @notice Get isMinted.
   */
  function getIsMinted(bytes32 instanceId) internal view returns (bool isMinted) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get isMinted.
   */
  function _getIsMinted(bytes32 instanceId) internal view returns (bool isMinted) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set isMinted.
   */
  function setIsMinted(bytes32 instanceId, bool isMinted) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((isMinted)), _fieldLayout);
  }

  /**
   * @notice Set isMinted.
   */
  function _setIsMinted(bytes32 instanceId, bool isMinted) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((isMinted)), _fieldLayout);
  }

  /**
   * @notice Get mintedTokenId.
   */
  function getMintedTokenId(bytes32 instanceId) internal view returns (uint256 mintedTokenId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get mintedTokenId.
   */
  function _getMintedTokenId(bytes32 instanceId) internal view returns (uint256 mintedTokenId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set mintedTokenId.
   */
  function setMintedTokenId(bytes32 instanceId, uint256 mintedTokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((mintedTokenId)), _fieldLayout);
  }

  /**
   * @notice Set mintedTokenId.
   */
  function _setMintedTokenId(bytes32 instanceId, uint256 mintedTokenId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((mintedTokenId)), _fieldLayout);
  }

  /**
   * @notice Get createdAt.
   */
  function getCreatedAt(bytes32 instanceId) internal view returns (uint256 createdAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get createdAt.
   */
  function _getCreatedAt(bytes32 instanceId) internal view returns (uint256 createdAt) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set createdAt.
   */
  function setCreatedAt(bytes32 instanceId, uint256 createdAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((createdAt)), _fieldLayout);
  }

  /**
   * @notice Set createdAt.
   */
  function _setCreatedAt(bytes32 instanceId, uint256 createdAt) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((createdAt)), _fieldLayout);
  }

  /**
   * @notice Get x.
   */
  function getX(bytes32 instanceId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get x.
   */
  function _getX(bytes32 instanceId) internal view returns (int32 x) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set x.
   */
  function setX(bytes32 instanceId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Set x.
   */
  function _setX(bytes32 instanceId, int32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Get y.
   */
  function getY(bytes32 instanceId) internal view returns (int32 y) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get y.
   */
  function _getY(bytes32 instanceId) internal view returns (int32 y) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set y.
   */
  function setY(bytes32 instanceId, int32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Set y.
   */
  function _setY(bytes32 instanceId, int32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Get z.
   */
  function getZ(bytes32 instanceId) internal view returns (int32 z) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get z.
   */
  function _getZ(bytes32 instanceId) internal view returns (int32 z) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 7, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set z.
   */
  function setZ(bytes32 instanceId, int32 z) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((z)), _fieldLayout);
  }

  /**
   * @notice Set z.
   */
  function _setZ(bytes32 instanceId, int32 z) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 7, abi.encodePacked((z)), _fieldLayout);
  }

  /**
   * @notice Get isOnGround.
   */
  function getIsOnGround(bytes32 instanceId) internal view returns (bool isOnGround) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get isOnGround.
   */
  function _getIsOnGround(bytes32 instanceId) internal view returns (bool isOnGround) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 8, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set isOnGround.
   */
  function setIsOnGround(bytes32 instanceId, bool isOnGround) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((isOnGround)), _fieldLayout);
  }

  /**
   * @notice Set isOnGround.
   */
  function _setIsOnGround(bytes32 instanceId, bool isOnGround) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setStaticField(_tableId, _keyTuple, 8, abi.encodePacked((isOnGround)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 instanceId) internal view returns (ItemInstanceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 instanceId) internal view returns (ItemInstanceData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 instanceId,
    uint16 itemId,
    address owner,
    bool isMinted,
    uint256 mintedTokenId,
    uint256 createdAt,
    int32 x,
    int32 y,
    int32 z,
    bool isOnGround
  ) internal {
    bytes memory _staticData = encodeStatic(itemId, owner, isMinted, mintedTokenId, createdAt, x, y, z, isOnGround);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 instanceId,
    uint16 itemId,
    address owner,
    bool isMinted,
    uint256 mintedTokenId,
    uint256 createdAt,
    int32 x,
    int32 y,
    int32 z,
    bool isOnGround
  ) internal {
    bytes memory _staticData = encodeStatic(itemId, owner, isMinted, mintedTokenId, createdAt, x, y, z, isOnGround);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 instanceId, ItemInstanceData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.itemId,
      _table.owner,
      _table.isMinted,
      _table.mintedTokenId,
      _table.createdAt,
      _table.x,
      _table.y,
      _table.z,
      _table.isOnGround
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 instanceId, ItemInstanceData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.itemId,
      _table.owner,
      _table.isMinted,
      _table.mintedTokenId,
      _table.createdAt,
      _table.x,
      _table.y,
      _table.z,
      _table.isOnGround
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint16 itemId,
      address owner,
      bool isMinted,
      uint256 mintedTokenId,
      uint256 createdAt,
      int32 x,
      int32 y,
      int32 z,
      bool isOnGround
    )
  {
    itemId = (uint16(Bytes.getBytes2(_blob, 0)));

    owner = (address(Bytes.getBytes20(_blob, 2)));

    isMinted = (_toBool(uint8(Bytes.getBytes1(_blob, 22))));

    mintedTokenId = (uint256(Bytes.getBytes32(_blob, 23)));

    createdAt = (uint256(Bytes.getBytes32(_blob, 55)));

    x = (int32(uint32(Bytes.getBytes4(_blob, 87))));

    y = (int32(uint32(Bytes.getBytes4(_blob, 91))));

    z = (int32(uint32(Bytes.getBytes4(_blob, 95))));

    isOnGround = (_toBool(uint8(Bytes.getBytes1(_blob, 99))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ItemInstanceData memory _table) {
    (
      _table.itemId,
      _table.owner,
      _table.isMinted,
      _table.mintedTokenId,
      _table.createdAt,
      _table.x,
      _table.y,
      _table.z,
      _table.isOnGround
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 instanceId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 instanceId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint16 itemId,
    address owner,
    bool isMinted,
    uint256 mintedTokenId,
    uint256 createdAt,
    int32 x,
    int32 y,
    int32 z,
    bool isOnGround
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(itemId, owner, isMinted, mintedTokenId, createdAt, x, y, z, isOnGround);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint16 itemId,
    address owner,
    bool isMinted,
    uint256 mintedTokenId,
    uint256 createdAt,
    int32 x,
    int32 y,
    int32 z,
    bool isOnGround
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(itemId, owner, isMinted, mintedTokenId, createdAt, x, y, z, isOnGround);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 instanceId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = instanceId;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
