import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    // API Documentation will be generated by TypeDoc
    // and added here automatically
  ],
};

export default sidebars;
