import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api/index',
        {
          type: 'category',
          label: 'Shared Package',
          items: [{type: 'autogenerated', dirName: 'api/shared'}],
        },
        {
          type: 'category',
          label: 'Client Package',
          items: [{type: 'autogenerated', dirName: 'api/client'}],
        },
        {
          type: 'category',
          label: 'Server Package',
          items: [{type: 'autogenerated', dirName: 'api/server'}],
        },
      ],
    },
  ],
};

export default sidebars;

