import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "API Reference",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
