// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSystem {
  function hyperscape__equipItem(uint8 inventorySlot) external;

  function hyperscape__unequipItem(uint8 equipSlot) external;
}
